resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/Sourcesetter/cjCon.git
    branch: master

- name: hello-world-docker-image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/concourse-hello-world

jobs:
- name: publish
  public: true
  plan:
  - get: git-resource
  - put: hello-world-docker-image
    params:
      build: git-resource/cjtests/docker-images/docker
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-hub-username))/concourse-hello-world
      run:
        path: /bin/hello-world
        args: []
      params:
        NAME: ((docker-hub-username))
