---
resources:
- name: cloud-resource
  type: git
  source:
    uri: https://github.com/Sourcesetter/cjCon.git
    branch: master 

jobs:
- name: job-exec-script
  public: true
  plan:
  - get: cloud-resource
  - task: exec-script
    file: cloud-resource/cjtests/pipe-skript/task.yml
