---
resources:
- name: cloud-resource
  type: git
  source:
    uri: https://github.com/Sourcesetter/cjCon.git
    branch: master

jobs:
- name: job-pass-files
  public: true
  plan:
  - get: cloud-resource
  - task: create-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}

      inputs:
      - name: cloud-resource
      outputs:
      - name: some-files

      run:
        path: cloud-resource/cjtests/task-io/create_some_files.sh

  - task: show-some-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}

      inputs:
      - name: cloud-resource
      - name: some-files

      run:
        path: cloud-resource/cjtests/task-io/show_files.sh

